import time

print('something')
# time.sleep(5)
print('something')
# time.sleep(10)
# print('something')
# time.sleep(10)
# print('something')
# time.sleep(10)
# print('something')
# time.sleep(10)
# print('something')
# time.sleep(10)
# print('something')