import time

print('something')
time.sleep(50)
print('something')
# time.sleep(10)
# print('something')
# time.sleep(10)
# print('something')
# time.sleep(10)
# print('something')
# time.sleep(10)
# print('something')
# time.sleep(10)
# print('something')